[project]
name = "asteroids"
version = "0.1.0"
description = "A simple Asteroids game implemented in Python using Pygame."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame==2.6.1",
]
